<!-- Admin Panel Block: Lower Left Homepage Image - Needs Renamed -->
<div class="image-seal">
<?php
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('lower_left_homepage_image')
        ->toHtml();
        ?>
</div>

<!-- Admin Panel Block: Footer Bottom -->
<div class="bottom-links">
<?php
        echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_bottom')
        ->toHtml();
        ?>
</div>